spring:
  application:
    name: jh-shop-es-service
#    TODO 后续解决一下不配置报错的问题 不需要数据库
  datasource:
    url: jdbc:mysql://localhost:3306/jh_shop_discount?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      rest:
        read-timeout: 5s
        connection-timeout: 3s
      repositories:
        enabled: true

feign:
  sentinel:
    enabled: true  # ?? Feign ? Sentinel ??
  client:
    config:
      default:
        connectTimeout: 5000  # ????
        readTimeout: 5000     # ????

server:
  port: 8083

logging:
  level:
    org.springframework: DEBUG
    pers.jhshop.user: DEBUG
    feign: DEBUG                # Feign?????
    com.alibaba.csp.sentinel: DEBUG  # ????Sentinel
    org.springframework.cloud.openfeign: DEBUG